name: Test and Deploy Serverless function

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@master
    - uses: vasiliybugaev/yandex-serverless-action@v1
      with:
        token: 'y0_AgAAAAAuCPTyAATuwQAAAAECUIk-AADzxIwMbUtEHIm86wfo61KlckZE3g'
        function_id: 'd4en0ut41fh82il4js27'
        runtime: 'python312'
        memory: '128'
        entrypoint: 'main.handler'
        source: '.'
        exclude: '(grammars)'
        description: 'guess the melody skill'